import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/ui/Header";
import Transisi from "@/components/Transisi";
import EfekTransisi from "@/components/EfekTransisi";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="shortcut icon" href="/logo.svg" type="image/x-icon" />
      <body className="overflow-hidden">
        <Header/>
        <EfekTransisi/>
        <Transisi>
        {children}
        </Transisi>
      </body>
    </html>
  );
}
